export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
export const REMOVE_FORM_ERRORS = 'REMOVE_FORM_ERRORS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
